ALTER TABLE "invoices" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "invoice_line_items" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payment_receipts" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "payment_reminder_logs" ENABLE ROW LEVEL SECURITY;
