ALTER TABLE "announcements" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "announcement_targets" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "announcement_reads" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "requests" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "request_activities" ENABLE ROW LEVEL SECURITY;
