CREATE TYPE "activity_action" AS ENUM ('ORG_CREATED','ORG_UPDATED','ORG_DELETED','ORG_MEMBER_INVITED','ORG_MEMBER_INVITE_ACCEPTED','ORG_MEMBER_INVITE_DECLINED','ORG_MEMBER_REMOVED','ORG_OWNERSHIP_TRANSFERRED','TOURNAMENT_CREATED','TOURNAMENT_UPDATED','TOURNAMENT_ARCHIVED','TOURNAMENT_UNARCHIVED','TOURNAMENT_DIRECTOR_ADDED','TOURNAMENT_DIRECTOR_REMOVED','CSV_IMPORT_STARTED','CSV_IMPORT_MAPPED','CSV_IMPORT_PROCESSED','CSV_IMPORT_NORMALIZATION_CONFIRMED','CSV_IMPORT_DIFF_APPLIED','CSV_IMPORT_FINALIZED','CSV_IMPORT_ROLLED_BACK','PORTAL_CLAIMED','PORTAL_TOKEN_REGENERATED','PORTAL_DISABLED','INSTITUTION_UPDATED','TEAM_CREATED','TEAM_UPDATED','TEAM_WITHDRAWN','PARTICIPANT_UPDATED','ADJUDICATOR_UPDATED','INVOICE_GENERATED','INVOICE_DISCOUNT_APPLIED','INVOICE_OVERRIDE_APPLIED','INVOICE_OVERRIDE_CLEARED','RECEIPT_SUBMITTED','RECEIPT_APPROVED','RECEIPT_REJECTED','REMINDER_SENT','ANNOUNCEMENT_CREATED','ANNOUNCEMENT_UPDATED','ANNOUNCEMENT_PUBLISHED','ANNOUNCEMENT_SCHEDULED','ANNOUNCEMENT_RETRACTED','REQUEST_SUBMITTED','REQUEST_MORE_INFO_REQUESTED','REQUEST_MORE_INFO_PROVIDED','REQUEST_APPROVED','REQUEST_REJECTED');

CREATE TABLE "activity_log" (
    "id" TEXT NOT NULL,
    "tournament_id" TEXT,
    "org_id" TEXT,
    "actor_id" TEXT,
    "actor_role_at_time" TEXT NOT NULL,
    "action" "activity_action" NOT NULL,
    "resource_type" TEXT NOT NULL,
    "resource_id" TEXT,
    "description" TEXT NOT NULL,
    "before_snapshot" JSONB,
    "after_snapshot" JSONB,
    "created_at" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT "activity_log_pkey" PRIMARY KEY ("id")
);
CREATE INDEX "activity_log_tournament_id_created_at_idx" ON "activity_log"("tournament_id", "created_at" DESC);
CREATE INDEX "activity_log_org_id_created_at_idx" ON "activity_log"("org_id", "created_at" DESC);
CREATE INDEX "activity_log_action_created_at_idx" ON "activity_log"("action", "created_at" DESC);
CREATE INDEX "activity_log_actor_id_created_at_idx" ON "activity_log"("actor_id", "created_at" DESC);
ALTER TABLE "activity_log" ADD CONSTRAINT "activity_log_tournament_id_fkey" FOREIGN KEY ("tournament_id") REFERENCES "tournaments"("id") ON DELETE CASCADE;
ALTER TABLE "activity_log" ADD CONSTRAINT "activity_log_org_id_fkey" FOREIGN KEY ("org_id") REFERENCES "organizations"("id") ON DELETE CASCADE;
ALTER TABLE "activity_log" ADD CONSTRAINT "activity_log_actor_id_fkey" FOREIGN KEY ("actor_id") REFERENCES "profiles"("id") ON DELETE SET NULL;

REVOKE UPDATE, DELETE ON activity_log FROM PUBLIC;
REVOKE UPDATE, DELETE ON activity_log FROM anon, authenticated, service_role;
